### PR TITLE
[2.7] [PR 62] Added docs for running GUI tests

### PR DESCRIPTION
**Pull request by mmattel**
Backport of #62

### CODE REVIEW

**Review by phil-davis — COMMENTED** [review]
@swoichha the instructions for running the tests will be correct for 2.7. But the actual tests might not pass (or work nicely). The 2.7 client might have different UI elements and the tests might not interact successfully with the 2.7 client UI.

After merging this PR, should we make a PR  to 2.7 branch to mention that?
Or not bother with this backport at all?

**Comment by mmattel** [comment]
please let me know how you want proceed.
fixing 2.7 or closing this PR - both is fine.
we can redo a backport when there is a fix available later on

**Comment by swoichha** [comment]
@phil-davis @mmattel I think we should close this PR because most of our test depends on different UI elements and it will be different in `2.7`. So many of test won't work.

**Comment by mmattel** [comment]
Closing with comment from @swoichha above.

**Pull request closed without merging**
