### PR TITLE
 Update 2.10.1 system requirements

### PR DESCRIPTION
**Pull request by gabi18**
and remove trailing dots on some msiexec commands

### CODE REVIEW

**Comment by gabi18** [comment]
Ubuntu 22.04 will be probably added - @fmoc is currently building...

**Comment by fmoc** [comment]
Ubuntu 22.04 is now supported. Fedora 36 is still causing some issues, but we're on it.

**Comment by gabi18** [comment]
> Ubuntu 22.04 is now supported. Fedora 36 is still causing some issues, but we're on it.

As Fedora 36 still isn't officially released we will add it for next version.

**Comment by gabi18** [comment]
@mmattel backport to 2.10 is needed

**Review by jnweiger — APPROVED** [review]
LGTM

**Pull request merged**
