### PR TITLE
Document OWNCLOUD_OVERRIDE_SERVER_URL environment variable

### PR DESCRIPTION
**Pull request by michaelstingl**
Implemented here: https://github.com/owncloud/client/pull/8772

@TheOneRing correct?

Backport to 2.9, not earlier!

### CODE REVIEW

**Comment by TheOneRing** [comment]
Do we want to promote that? I thought that is only for dev use ...

**Comment by michaelstingl** [comment]
Yes, this is what this page is about:

> Most environment variables only exist for debugging or testing. They are not officially supported and may change from version to version. If you end up relying on a setting only available through an environment variable, please create a bug report.

**Review by TheOneRing — APPROVED** [review]
Looks correct

**Comment by mmattel** [comment]
just rebased due to recent changes

**Pull request merged**
